api:
  build: .
  command: "config/container/start-server-dev.sh -bash"
  volumes:
    - .:/app
    - ./config/container/dev/ssl:/etc/secrets
  ports:
    - "3000:3000"
  links:
    - db
    - kong
    - redis
    - elasticsearch
  environment:
    S3_BUCKET_NAME: "retiqueta-dev-images"
    AWS_ACCESS_KEY_ID: "AKIAINKHBRALJ2V7JMDQ"
    AWS_SECRET_ACCESS_KEY: "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"
    REDIS_SERVICE_HOST: "redis"
    REDIS_SERVICE_PORT: "6379"
    SMTP_USER_NAME: dextrin.diorman@gmail.com
    SMTP_PASSWORD: u7uu24nmtB47K9YigTyThg
    ML_VE_PUBLIC_KEY: TEST-f4c0a8de-a40c-46c2-90f9-202e66994dd3
    ML_VE_ACCESS_TOKEN: TEST-7996492241102187-020901-2125bf21d3eda6d5c1150a3ae949e743__LD_LB__-203200861
    SECRET_PATHS: "/etc/secrets"
    FB_CLIENT_ID: 218604841833703
    FB_CLIENT_SECRET: 222c4b672075027ad2ba34ee81a4ce5e
    KONG_ADMIN_SERVICE_HOST: kong
    KONG_ADMIN_SERVICE_PORT: 8001
    MIXPANEL_TOKEN: "5c8d640c06abde316d620efc36cdadc2"
    IONIC_ACCESS_TOKEN:
    UPSTREAM_SERVICE_HOST:
worker:
  build: .
  command: "config/container/start-workers.sh -bash"
  volumes:
    - .:/app
  links:
    - elasticsearch
    - db
    - redis
    - kong
  environment:
    S3_BUCKET_NAME: "retiqueta-dev-images"
    AWS_ACCESS_KEY_ID: "AKIAINKHBRALJ2V7JMDQ"
    AWS_SECRET_ACCESS_KEY: "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"
    REDIS_SERVICE_HOST: "redis"
    REDIS_SERVICE_PORT: "6379"
    SMTP_USER_NAME: dextrin.diorman@gmail.com
    SMTP_PASSWORD: u7uu24nmtB47K9YigTyThg
    SECRET_PATHS: "/etc/secrets"
    MIXPANEL_TOKEN: "5c8d640c06abde316d620efc36cdadc2"
    ML_VE_PUBLIC_KEY: TEST-f4c0a8de-a40c-46c2-90f9-202e66994dd3
    ML_VE_ACCESS_TOKEN: TEST-7996492241102187-020901-2125bf21d3eda6d5c1150a3ae949e743__LD_LB__-203200861
kong:
  image: rafael/kong:0.8.3postgres
  ports:
    - "80:8000"
    - "443:8443"
    - "8001:8001"
  environment:
    PG_HOST: db
    PG_PASSWORD: 123456
    PG_USER: root
    PG_PORT: 5432
    PG_DATABASE: postgres
    DATABASE: postgres
  links:
    - db
redis:
 image: library/redis:2.6.17
 ports:
   - "6379:6379"
db:
  image: library/postgres:9.5.3
  ports:
    - "5432:5432"
  environment:
    POSTGRES_PASSWORD: 123456
    POSTGRES_USER: root
elasticsearch:
  build: ./docker/elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
