api:
  build: .
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - db
    - kong
    - redis
    - elasticsearch
  environment:
    S3_BUCKET_NAME: "retiqueta-dev-images"
    AWS_ACCESS_KEY_ID: "AKIAJPD6UFMMPDH2LNZA"
    AWS_SECRET_ACCESS_KEY: "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"
    MYSQL_ROOT_PASSWORD: 123456
    REDIS_SERVICE_HOST: "redis"
    REDIS_SERVICE_PORT: "6379"
worker:
  build: .
  command: bundle exec sidekiq -C config/sidekiq.yml
  volumes:
    - .:/app
  links:
    - elasticsearch
    - db
    - redis
    - kong
  environment:
    S3_BUCKET_NAME: "retiqueta-dev-images"
    AWS_ACCESS_KEY_ID: "AKIAJPD6UFMMPDH2LNZA"
    AWS_SECRET_ACCESS_KEY: "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"
    MYSQL_ROOT_PASSWORD: 123456
    REDIS_SERVICE_HOST: "redis"
    REDIS_SERVICE_PORT: "6379"
redis:
 image: library/redis:2.6.17
 ports:
   - "6379:6379"
db:
  image: library/mysql:5.6.22
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
kong:
  image: rafael/kong:0.5.1
  ports:
    - "8000:8000"
    - "8443:8443"
    - "8001:8001"
  links:
    - cassandra
cassandra:
  image: mashape/cassandra
  ports:
    - "9042:9042"
elasticsearch:
  image: library/elasticsearch:1.7.1
  ports:
    - "9200:9200"
    - "9300:9300"
