default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: sam737446
  host: localhost

development:
  <<: *default
  database: retiqueta_api_development

test:
  <<: *default
  database: retiqueta_api_test

production:
  <<: *default
  database: retiqueta_api_production
  username: <%= ENV['RETIQUETA_API_DATABASE_USER'] %>
  password: <%= ENV['RETIQUETA_API_DATABASE_PASSWORD'] %>
  host: <%= ENV['MYSQL_SERVICE_HOST'] %>
