consumer:
  username: retiqueta

outh2_application:
  name: dev-app
  redirect_uri: http://redirect.uri

apis:
  -
    name: products-resource
    request_path: /v1/products
    strip_request_path: true
    upstream_url: http://<%= ENV["API_IP_PORT"] %>/v1/products
  -
    name: users-resource
    request_path: /v1/users
    strip_request_path: true
    upstream_url: http://<%= ENV["API_IP_PORT"] %>/v1/users
  -
    name: authenticate-resource
    request_path: /v1/authenticate
    strip_request_path: true
    upstream_url: http://<%= ENV["API_IP_PORT"] %>/v1/authenticate
  -
    name: product-pictures-resource
    request_path: /v1/product_pictures
    strip_request_path: true
    upstream_url: http://<%= ENV["API_IP_PORT"] %>/v1/product_pictures
  -
    name: registrations-resource
    request_path: /v1/registrations
    strip_request_path: true
    upstream_url: http://<%= ENV["API_IP_PORT"] %>/v1/registrations

plugins:
  -
    name: oauth2
    config.scopes: app
    config.mandatory_scope: true
    config.enable_password_grant: true
    apis:
      - products-resource
      - users-resource
      - product-pictures-resource
