consumer:
  username: retiqueta

outh2_application:
  name: dev-app
  redirect_uri: http://redirect.uri

apis:
  -
    name: public-endpoints
    request_path: /v1/public
    preserve_host: true
    upstream_url: http://<%= ENV.fetch("UPSTREAM_SERVICE_HOST", "retiqueta.default.svc.cluster.local") %>:<%= ENV.fetch("UPSTREAM_SERVICE_PORT",  3000) %>
  -
    name: api-admin-resource
    request_path: /admin
    strip_request_path: true
    upstream_url: http://<%= ENV.fetch("UPSTREAM_SERVICE_HOST", "retiqueta.default.svc.cluster.local") %>:<%= ENV.fetch("UPSTREAM_SERVICE_PORT",  3000) %>/admin
  -
    name: products-resource
    request_path: /v1/products
    strip_request_path: true
    upstream_url: http://<%= ENV.fetch("UPSTREAM_SERVICE_HOST", "retiqueta.default.svc.cluster.local") %>:<%= ENV.fetch("UPSTREAM_SERVICE_PORT",  3000) %>/v1/products
  -
    name: users-resource
    request_path: /v1/users
    strip_request_path: true
    upstream_url: http://<%=  ENV.fetch("UPSTREAM_SERVICE_HOST", "retiqueta.default.svc.cluster.local") %>:<%= ENV.fetch("UPSTREAM_SERVICE_PORT", 3000) %>/v1/users
  -
    name: authenticate-resource
    request_path: /v1/authenticate
    strip_request_path: true
    upstream_url: http://<%=  ENV.fetch("UPSTREAM_SERVICE_HOST", "retiqueta.default.svc.cluster.local") %>:<%= ENV.fetch("UPSTREAM_SERVICE_PORT", 3000) %>/v1/authenticate
  -
    name: product-pictures-resource
    request_path: /v1/product_pictures
    strip_request_path: true
    upstream_url: http://<%=  ENV.fetch("UPSTREAM_SERVICE_HOST", "retiqueta.default.svc.cluster.local") %>:<%= ENV.fetch("UPSTREAM_SERVICE_PORT", 3000) %>/v1/product_pictures
  -
    name: registrations-resource
    request_path: /v1/registrations
    strip_request_path: true
    upstream_url: http://<%=  ENV.fetch("UPSTREAM_SERVICE_HOST", "retiqueta.default.svc.cluster.local") %>:<%= ENV.fetch("UPSTREAM_SERVICE_PORT", 3000) %>/v1/registrations
  -
    name: ionic-webhook
    request_path: /e22e9a38-cd10-4132-b2d3-a845b0aa0539
    strip_request_path: true
    upstream_url: http://<%=  ENV.fetch("UPSTREAM_SERVICE_HOST", "retiqueta.default.svc.cluster.local") %>:<%= ENV.fetch("UPSTREAM_SERVICE_PORT", 3000) %>/e22e9a38-cd10-4132-b2d3-a845b0aa0539
  -
    name: send-password-reset
    request_path: /v1/send_password_reset
    strip_request_path: true
    upstream_url: http://<%=  ENV.fetch("UPSTREAM_SERVICE_HOST", "retiqueta.default.svc.cluster.local") %>:<%= ENV.fetch("UPSTREAM_SERVICE_PORT", 3000) %>/v1/send_password_reset
  -
    name: reset-password
    request_path: /v1/reset_password
    strip_request_path: true
    upstream_url: http://<%=  ENV.fetch("UPSTREAM_SERVICE_HOST", "retiqueta.default.svc.cluster.local") %>:<%= ENV.fetch("UPSTREAM_SERVICE_PORT", 3000) %>/v1/reset_password
  -
    name: sales-resource
    request_path: /v1/sales
    strip_request_path: true
    upstream_url: http://<%=  ENV.fetch("UPSTREAM_SERVICE_HOST", "retiqueta.default.svc.cluster.local") %>:<%= ENV.fetch("UPSTREAM_SERVICE_PORT", 3000) %>/v1/sales
  -
    name: orders-resource
    request_path: /v1/orders
    strip_request_path: true
    upstream_url: http://<%=  ENV.fetch("UPSTREAM_SERVICE_HOST", "retiqueta.default.svc.cluster.local") %>:<%= ENV.fetch("UPSTREAM_SERVICE_PORT", 3000) %>/v1/orders
  -
    name: fulfillments-resource
    request_path: /v1/fulfillments
    strip_request_path: true
    upstream_url: http://<%=  ENV.fetch("UPSTREAM_SERVICE_HOST", "retiqueta.default.svc.cluster.local") %>:<%= ENV.fetch("UPSTREAM_SERVICE_PORT", 3000) %>/v1/fulfillments
  -
    name: payouts-resource
    request_path: /v1/payouts
    strip_request_path: true
    upstream_url: http://<%=  ENV.fetch("UPSTREAM_SERVICE_HOST", "retiqueta.default.svc.cluster.local") %>:<%= ENV.fetch("UPSTREAM_SERVICE_PORT", 3000) %>/v1/payouts
  -
    name: admin-www
    upstream_url: http://<%=  ENV.fetch("UPSTREAM_SERVICE_HOST", "retiqueta-www.default.svc.cluster.local") %>:<%= ENV.fetch("UPSTREAM_SERVICE_PORT", 3000) %>
    request_host: admin.retiqueta.com
  -
    name: ops-resource
    request_path: /ops/status
    strip_request_path: true
    upstream_url: http://<%=  ENV.fetch("UPSTREAM_SERVICE_HOST", "retiqueta.default.svc.cluster.local") %>:<%= ENV.fetch("UPSTREAM_SERVICE_PORT", 3000) %>/ops/status
  -
    name: mandrill-webhook
    request_path:  /8e6fd49b-8d40-4741-88d0-0633e3568cac
    strip_request_path: true
    upstream_url: http://<%=  ENV.fetch("UPSTREAM_SERVICE_HOST", "retiqueta.default.svc.cluster.local") %>:<%= ENV.fetch("UPSTREAM_SERVICE_PORT", 3000) %>/8e6fd49b-8d40-4741-88d0-0633e3568cac
  -
    name: timeline-resources
    request_path: /v1/timeline
    strip_request_path: true
    upstream_url: http://<%=  ENV.fetch("UPSTREAM_SERVICE_HOST", "retiqueta.default.svc.cluster.local") %>:<%= ENV.fetch("UPSTREAM_SERVICE_PORT", 3000) %>/v1/timeline

plugins:
  -
    name: request-transformer
    config.add.headers: "x_forwarded_host: admin.retiqueta.com ,x_forwarded_port: 80"
    apis:
      - admin-www
  -
    name: request-transformer
    config.add.headers: "x_forwarded_host:<%= Rails.configuration.x.kong.external_host %>,x_forwarded_port:<%= Rails.configuration.x.kong.external_port %>"
    apis: all
  -
    name: cors
    apis: all
  -
    name: ssl
    apis: all
    config.cert: "<%= IO.read('/etc/secrets/retiqueta-ssl-api-pem') %>" # Have to find a way to do this with faraday :/
    config.key: "<%=  IO.read('/etc/secrets/retiqueta-ssl-api-key') %>"
    config.only_https: "true"
  -
    name: oauth2
    config.scopes: app
    config.mandatory_scope: true
    config.enable_password_grant: true
    config.token_expiration: 72000
    apis:
      - api-admin-resource
      - products-resource
      - users-resource
      - product-pictures-resource
      - orders-resource
      - sales-resource
      - fulfillments-resource
      - payouts-resource
