default: &default
  secret_key_base: 9d4a19189a71ba30c5475edfdf961bd5d2d044b9666b2a04d6616a27613bb5fb19406cdb7c4cbb81521abbba71d416453611e31f31815e5330e79df208bcee2e
  kong_client_secret: <%= ENV["KONG_CLIENT_SECRET"] %>
  kong_client_id: <%= ENV["KONG_CLIENT_ID"] %>
  kong_client_provision_key: <%= ENV["KONG_CLIENT_PROVISION_KEY"] %>
  smtp_user_name: <%= ENV["SMTP_USER_NAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  mercado_pago_ve_public_key: <%= ENV['ML_VE_PUBLIC_KEY'] %>
  mercado_pago_ve_access_token: <%= ENV['ML_VE_ACCESS_TOKEN'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
