---
http_interactions:
- request:
    method: post
    uri: https://gcm-http.googleapis.com/gcm/send
    body:
      encoding: UTF-8
      string: "{}"
    headers:
      User-Agent:
      - Faraday v0.9.2
      Content-Type:
      - application/json
      Authorization:
      - key=AIzaSyCSCRFDr89Mih_3niJ2uzqbGudO6aFkCq8
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 401
      message: Unauthorized
    headers:
      Content-Type:
      - text/html; charset=UTF-8
      Date:
      - Fri, 30 Oct 2015 16:41:10 GMT
      Expires:
      - Fri, 30 Oct 2015 16:41:10 GMT
      Cache-Control:
      - private, max-age=0
      X-Content-Type-Options:
      - nosniff
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      Server:
      - GSE
      Alternate-Protocol:
      - 443:quic,p=1
      Alt-Svc:
      - quic=":443"; p="1"; ma=604800
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: |
        <HTML>
        <HEAD>
        <TITLE>Unauthorized</TITLE>
        </HEAD>
        <BODY BGCOLOR="#FFFFFF" TEXT="#000000">
        <H1>Unauthorized</H1>
        <H2>Error 401</H2>
        </BODY>
        </HTML>
    http_version:
  recorded_at: Fri, 30 Oct 2015 16:41:17 GMT
recorded_with: VCR 2.9.3
